# Generated by Django 4.2.3 on 2023-08-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type1', models.CharField(max_length=100)),
                ('type2', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=150)),
                ('attack1', models.CharField(max_length=250)),
                ('attack2', models.CharField(max_length=250)),
                ('attack3', models.CharField(max_length=250)),
                ('attack4', models.CharField(max_length=250)),
                ('nature', models.CharField(max_length=100)),
                ('ev1', models.CharField(max_length=100)),
                ('ev2', models.CharField(max_length=100)),
                ('ev3', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
