# Generated by Django 4.2.3 on 2023-09-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_trainer_imagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='imageName',
            new_name='subClass',
        ),
    ]
