# Generated by Django 4.2.3 on 2023-08-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_pokemon_attack2_alter_pokemon_attack3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ev4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='ev1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='ev2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
